# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-17 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
