# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-18 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
