# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-18 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_us_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author22222222222222222222',
        ),
    ]
